### ISSUE TITLE
Mapping to local user with passwd

### ISSUE THREAD

**Issue by bacharya** [daveolson53/libtacplus-map#2]
Hi,

  I'm trying to map tacacs user to the local user with passwd and but tacacs user doesn't able to login, though the tacacs user is successfully authenticated by the tacacs server:

auth.log:

_Nov 11 10:49:00 localhost sshd[587]: nss_tacplus: TACACS+ server 10.0.3.227:49 successful for user bhishma
Nov 11 10:49:03 localhost sshd[587]: nss_tacplus: TACACS+ server 10.0.3.227:49 successful for user bhishma
Nov 11 10:49:05 localhost sshd[587]: Failed password for bhishma from 10.0.3.1 port 60488 ssh2_

In the README i see below statement:
    The TACACS+ users do not need entries in /etc/passwd to supply home directory, uid,
    and gid information.

Any feasible solutions or workarounds?

TIA

**Comment by daveolson53** [comment]
Sorry, I remember this issue, and that it's a configuration issue, but no details.  Should it still matter, go through the docs.
